import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property<int> counter:   42;
    callback request-increase-value();
    callback runPythonScript();
    VerticalBox {   
        Text {
            text: "Counter: \{root.counter}";
        }
        Button {
            text: "Increase value";
            clicked => {   
                root.request-increase-value();
            }
        }
        Button {
            text: "Run Python Script";
            clicked => {   
                // Rufen Sie die Methode im Backend auf, die das Python-Skript startet
                root.runPythonScript();
                //window.runPythonScript();
            }
        }
    }
}