[package]
name = "kubyplexer-ui"
version = "0.1.0"
authors = ["root"]
edition = "2021"
build = "build.rs"
[features]
nightly = []
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
serde_json = "1.0"
lazy_static = "1.4.0"

serde = "1.0.133"
serde_derive = "1.0.133"
k8s-openapi = { version = "0.12.0", features = ["v1_18"] }
kube = "0.58.0"
tokio = { version = "1", features = ["full"] }
slint = "1.4"
winit = "0.29.10"
notify = "5.0.0-pre.2"

[build-dependencies]
slint-build = "1.4"

